apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server-container
        image: aaronv70/server-app:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  type: ClusterIP 
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 